package errs

import "errors"

// Validation Errors
var (
	ErrInvalidData              = errors.New("ErrInvalidData")
	ErrValidationFailed         = errors.New("ErrValidationFailed")
	ErrPathParametrized         = errors.New("ErrPathParametrized")
	ErrInvalidMinPrice          = errors.New("ErrInvalidMinPrice")
	ErrInvalidMaxPrice          = errors.New("ErrInvalidMaxPrice")
	ErrInvalidRecommendIDs      = errors.New("ErrInvalidRecommendIDs")
	ErrInvalidType              = errors.New("ErrInvalidType")
	ErrInvalidAmount            = errors.New("ErrInvalidAmount")
	ErrInvalidPrice             = errors.New("ErrInvalidPrice")
	ErrInsufficientFunds        = errors.New("ErrInsufficientFunds")
	ErrOrderAlreadyPayed        = errors.New("ErrOrderAlreadyPayed")
	ErrInvalidCategory          = errors.New("ErrInvalidCategory")
	ErrInvalidStore             = errors.New("ErrInvalidStore")
	ErrOrderHasBeenPaidFor      = errors.New("ErrOrderHasBeenPaidFor")
	ErrInvalidDate              = errors.New("start or end date is not set")
	ErrEndDateBeforeStartDate   = errors.New("end date must be after start date")
	ErrInvalidID                = errors.New("ErrInvalidID")
	ErrInvalidCourseID          = errors.New("ErrInvalidCourseID")
	ErrInvalidPaymentID         = errors.New("ErrInvalidPaymentID")
	ErrInvalidOrderID           = errors.New("ErrInvalidOrderID")
	ErrInvalidQuantity          = errors.New("ErrInvalidQuantity")
	ErrInvalidFeaturedProductID = errors.New("ErrInvalidFeaturedProductID")
	ErrInvalidAccountID         = errors.New("ErrInvalidAccountID")
	ErrInvalidAddressID         = errors.New("ErrInvalidAddressID")
	ErrInvalidProductID         = errors.New("ErrInvalidProductID")
	ErrInvalidProductReviewID   = errors.New("ErrInvalidProductReviewID")
	ErrInvalidStoreID           = errors.New("ErrInvalidStoreID")
	ErrInvalidStoreReviewID     = errors.New("ErrInvalidStoreReviewID")
	ErrInvalidComment           = errors.New("ErrInvalidComment")
	ErrInvalidContent           = errors.New("ErrInvalidContent")
	ErrInvalidBalance           = errors.New("ErrInvalidBalance")
	ErrInvalidRating            = errors.New("ErrInvalidRating")
	ErrInvalidVacancyID         = errors.New("ErrInvalidVacancyID")
	ErrInvalidTitle             = errors.New("ErrInvalidTitle")
	ErrInvalidToken             = errors.New("ErrInvalidToken")
	ErrNotEnoughProductInStock  = errors.New("ErrNotEnoughProductInStock")
	ErrRefreshTokenExpired      = errors.New("ErrRefreshTokenExpired")
	ErrInvalidAddressName       = errors.New("ErrInvalidAddressName")
	ErrInvalidAccountNumber     = errors.New("ErrInvalidAccountNumber")
	ErrInvalidDescription       = errors.New("ErrInvalidDescription")
	ErrUserIDIsEmpty            = errors.New("ErrUserIDIsEmpty")
	ErrCodeIsEmpty              = errors.New("ErrCodeIsEmpty")
	ErrIPIsEmpty                = errors.New("ErrIPIsEmpty")
	ErrProjectIDIsEmpty         = errors.New("ErrProjectIDIsEmpty")
	ErrValueIsEmpty             = errors.New("ErrValueIsEmpty")
	ErrProjectIsUnactive        = errors.New("ErrProjectIsUnactive")
)
